development:
  secret_key_base: 4f98bc41312efa639af653574eb49d6cd25f397f60d8f1fa55a5a8dc1913920e8f14265ad8fdf9ab7df406ae6790eab3ea85ddb7531aa726f50085e86950966f
  sso_secret_key_base: 11f47da88f28f287add2221f081f3972af887cec7649650e1eb4728a6b4e9f3814cdd6632e7b550704cb90ffd15183cc53d6beb31e7d5a2112b891dc807be21c
  sso_encrypted_cookie_salt: 'Zx4?=P:soCe|l-Ib={iPikI5lty,-Cd<LC7gPxoOY4/g5HxG,4nGDj)wsfl|:65;'
  sso_encrypted_signed_cookie_salt: '$Y8WOE[kfE(|::q|P#LgINM4]^&>!&5O*xCOcO~ka74d$-*xxZI+NKsNgTrtB$9#'

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sso_secret_key_base: <%= ENV["SSO_SECRET_KEY_BASE"] %>
  sso_encrypted_cookie_salt: <%= ENV["SSO_ENCRYPTED_COOKIE_SALT"] %>
  sso_encrypted_signed_cookie_salt: <%= ENV["SSO_ENCRYPTED_SIGNED_COOKIE_SALT"] %>
  sso_session_key: <%= ENV["SSO_SESSION_KEY"] %>

test:
  secret_key_base: 7f86b1c8769c7251945d25f2537abd03660cec4e652b9d66d0e1cee7feb57e50a54a3ab2176c087befdac8813e5d5a9603f2fa0c690ce04ccd494324f0d9b8df
